version: '3'
services:
  poc_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: gh_action_poc
    restart: ${GOR_RESTART_SERVICES:-always}
    working_dir: /app
    volumes:
      - ./app:/app/
    ports:
      - 8000:8000
